stages:
  - test

run-tests:
  stage: test
  image: cypress/included:9.6.1
  script:
    - echo "Running all Cypress tests..."
    - cypress run --browser chrome --headless --spec 'cypress/e2e/tests/**/*.cy.js'
